version: '3.8'

services:
  voice-cloning-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./voice_embeddings:/app/voice_embeddings
      - ./logs:/app/logs
      - ./cache:/app/.cache  # <-- new
    environment:
      - PORT=8000
      - DEVICE=auto
      - LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
